// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc1
// source: proto/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeProcessor_ProcessCode_FullMethodName = "/CodeProcessor/ProcessCode"
)

// CodeProcessorClient is the client API for CodeProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeProcessorClient interface {
	ProcessCode(ctx context.Context, in *Code, opts ...grpc.CallOption) (*Vulnerability, error)
}

type codeProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeProcessorClient(cc grpc.ClientConnInterface) CodeProcessorClient {
	return &codeProcessorClient{cc}
}

func (c *codeProcessorClient) ProcessCode(ctx context.Context, in *Code, opts ...grpc.CallOption) (*Vulnerability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vulnerability)
	err := c.cc.Invoke(ctx, CodeProcessor_ProcessCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeProcessorServer is the server API for CodeProcessor service.
// All implementations must embed UnimplementedCodeProcessorServer
// for forward compatibility.
type CodeProcessorServer interface {
	ProcessCode(context.Context, *Code) (*Vulnerability, error)
	mustEmbedUnimplementedCodeProcessorServer()
}

// UnimplementedCodeProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeProcessorServer struct{}

func (UnimplementedCodeProcessorServer) ProcessCode(context.Context, *Code) (*Vulnerability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessCode not implemented")
}
func (UnimplementedCodeProcessorServer) mustEmbedUnimplementedCodeProcessorServer() {}
func (UnimplementedCodeProcessorServer) testEmbeddedByValue()                       {}

// UnsafeCodeProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeProcessorServer will
// result in compilation errors.
type UnsafeCodeProcessorServer interface {
	mustEmbedUnimplementedCodeProcessorServer()
}

func RegisterCodeProcessorServer(s grpc.ServiceRegistrar, srv CodeProcessorServer) {
	// If the following call pancis, it indicates UnimplementedCodeProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeProcessor_ServiceDesc, srv)
}

func _CodeProcessor_ProcessCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Code)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeProcessorServer).ProcessCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeProcessor_ProcessCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeProcessorServer).ProcessCode(ctx, req.(*Code))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeProcessor_ServiceDesc is the grpc.ServiceDesc for CodeProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CodeProcessor",
	HandlerType: (*CodeProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessCode",
			Handler:    _CodeProcessor_ProcessCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
